import { CreateModuleInput, ModuleDifficulty } from "@/lib/graphql/API";

const modulesSeedData: [CreateModuleInput, ...CreateModuleInput[]] = [
  {
    id: "module-001",
    courseId: "aws-cloud-essentials",
    slug: "cloud-computing-fundamentals",
    title: "Cloud Computing Fundamentals",
    description: "Learn the core concepts of cloud computing and its benefits.",
    order: 1,
    difficulty: ModuleDifficulty.BEGINNER,
  },
  {
    id: "module-002",
    courseId: "aws-cloud-essentials",
    slug: "setting-up-your-aws-account",
    title: "Setting Up Your AWS Account",
    description: "Learn how to create and configure your AWS account.",
    order: 2,
    difficulty: ModuleDifficulty.BEGINNER,
  },
  {
    id: "module-003",
    courseId: "aws-cloud-essentials",
    slug: "understanding-aws-infrastructure",
    title: "Understanding AWS Infrastructure",
    description: "Explore AWS Regions, Availability Zones, and Edge Locations.",
    order: 3,
    difficulty: ModuleDifficulty.BEGINNER,
  },
  {
    id: "module-004",
    courseId: "aws-cloud-essentials",
    slug: "compute-services-in-aws",
    title: "Compute Services in AWS",
    description: "Learn about EC2, Lambda, and other compute options.",
    order: 4,
    difficulty: ModuleDifficulty.INTERMEDIATE,
  },
  {
    id: "module-005",
    courseId: "aws-cloud-essentials",
    slug: "storage-services-in-aws",
    title: "Storage Services in AWS",
    description: "Explore S3, EBS, and other storage solutions.",
    order: 5,
    difficulty: ModuleDifficulty.INTERMEDIATE,
  },
  {
    id: "module-006",
    courseId: "aws-cloud-essentials",
    slug: "database-services-in-aws",
    title: "Database Services in AWS",
    description: "Learn about RDS, DynamoDB, and other database options.",
    order: 6,
    difficulty: ModuleDifficulty.INTERMEDIATE,
  },
  {
    id: "module-007",
    courseId: "aws-cloud-essentials",
    slug: "networking-in-aws",
    title: "Networking in AWS",
    description: "Understand VPCs, subnets, and routing.",
    order: 7,
    difficulty: ModuleDifficulty.INTERMEDIATE,
  },
  {
    id: "module-008",
    courseId: "aws-cloud-essentials",
    slug: "security-fundamentals-in-aws",
    title: "Security Fundamentals in AWS",
    description: "Learn about IAM, security groups, and best practices.",
    order: 8,
    difficulty: ModuleDifficulty.INTERMEDIATE,
  },
  {
    id: "module-009",
    courseId: "aws-cloud-essentials",
    slug: "introduction-to-serverless",
    title: "Introduction to Serverless",
    description: "Explore serverless computing with Lambda and API Gateway.",
    order: 9,
    difficulty: ModuleDifficulty.INTERMEDIATE,
  },
  {
    id: "module-010",
    courseId: "aws-cloud-essentials",
    slug: "monitoring-and-logging-in-aws",
    title: "Monitoring and Logging in AWS",
    description:
      "Learn about CloudWatch, CloudTrail, and other monitoring tools.",
    order: 10,
    difficulty: ModuleDifficulty.ADVANCED,
  },
  {
    id: "module-011",
    courseId: "aws-cloud-essentials",
    slug: "cost-management-in-aws",
    title: "Cost Management in AWS",
    description: "Understand how to manage and optimize AWS costs.",
    order: 11,
    difficulty: ModuleDifficulty.ADVANCED,
  },
  {
    id: "module-012",
    courseId: "aws-cloud-essentials",
    slug: "introduction-to-devops-in-aws",
    title: "Introduction to DevOps in AWS",
    description: "Learn about CI/CD pipelines and infrastructure as code.",
    order: 12,
    difficulty: ModuleDifficulty.ADVANCED,
  },
];
export default modulesSeedData;
